Repository Penguins-ims-india/Mental-Health-App, pull requests merged in 2024-05, with the labels that each got.

#9 FEAT / seed added seed function
  package-lock.json
  package.json
  server/db/index.js
  server/db/seed.js
Labels: READY

#11 FIX Seed Command can now be run
  client/src/components/Habits.jsx
  package.json
  server/db/index.js
  server/db/seed.js
  server/index.js
Labels: bug, READY

#17 Delete client/dist directory
  .gitignore
  client/dist/0515ab82dae6923cab85.woff
  client/dist/1431d1cef06ad04f5458.woff2
  client/dist/169619821ea93019d1bb.woff2
  client/dist/182712ab85f1472cdb2f.woff
  client/dist/198a421f279162d59143.woff
  client/dist/1a05a4887ccb810cb4dd.woff
  client/dist/1f075502d0094a398e21.woff
  client/dist/227c93190fe7f82de3f8.woff2
  client/dist/249853776d22a271b2b5.woff
  client/dist/252057e589a0379208ed.woff
  client/dist/268f264f58eba5c07c88.woff
  client/dist/3230f9b040f3c630e0c3.woff2
  client/dist/32fc45a3d1e8ea11fabc.woff2
  client/dist/3425a701027d0699e369.woff2
  client/dist/3503ec5cc6330e21f695.woff
  client/dist/35b9d6be04b95f0f0530.woff2
  client/dist/392a45a84c081c4b412d.woff
  client/dist/3f2b9a42f643e62a49b7.woff
  client/dist/4777461b144e55145268.woff2
  client/dist/4df79f684fcbca8386bd.woff
  client/dist/50e795c1345353b0e996.woff2
  client/dist/5b5f2f31962967dfc22c.woff
  client/dist/62ced72e5832f02c2796.woff2
  client/dist/657896dad292ee9a0a0a.woff
  client/dist/666d7a2f9db53cf52e2d.woff
  client/dist/6fb9cffb1d3e72bf9293.woff2
  client/dist/71a33b6b50457b2c903a.woff2
  client/dist/804378952da8a10faae2.woff2
  client/dist/8472d69545c7409091b4.woff
  client/dist/861b791f9de857a6e7bc.woff2
  client/dist/8ecd7085cfe9bc2c22ac.woff
  client/dist/9165081d10e1ba601384.woff2
  client/dist/965aebef74db72eaf236.woff
  client/dist/9ac81fefbe6c319ea40b.woff2
  client/dist/a84892c56152037b3552.woff
  client/dist/af4d91666ea345601bea.woff
  client/dist/b009a76ad6afe4ebd301.woff2
  client/dist/bd9854c751441ccc1a70.woff2
  client/dist/be4d02458ce53887dc37.woff2
  client/dist/c1cc6d6fc851b3a2f79d.woff
  client/dist/c1d66054fe23e181d92c.woff
  client/dist/c35e4c3958e209d17b31.woff2
  client/dist/c48fb6765a9fcb00b330.woff2
  client/dist/cad7d3d9cb265e334e58.woff2
  client/dist/d010f1f324e111a22e53.woff2
  client/dist/d8642a3d1d4ef6179644.woff2
  client/dist/db2632771401f61463fe.woff2
  client/dist/dc7dcec8e3f654e0ed63.woff2
  client/dist/dfdff8fa12eac629d29f.woff
  client/dist/e0e8ba725ebd107367a8.woff
  client/dist/e757c42df6aaa3e11b62.woff
  client/dist/eaa367bbd0b333a7f80b.woff
  client/dist/ed67ad54b1a8f5d21150.woff2
  client/dist/f25d774ecfe0996f8eb5.woff2
  client/dist/f708607d2a7290fb8bfa.woff
  client/dist/f8a034d72aa6828199d4.woff
  client/dist/index.html
Labels: READY

#18 FEAT / fixed weather api and did initial homePage styling
  .gitignore
  client/src/components/App.jsx
  client/src/components/HomePage.jsx
  server/routers/weatherController.js
Labels: READY

#20 FEAT / navbar added functional navbar
  client/index.html
  client/src/components/App.jsx
  client/src/components/Journal.jsx
  client/src/components/JournalBar.jsx
  client/src/components/JournalBarItem.jsx
  client/src/components/NavBar.jsx
  package-lock.json
Labels: READY

#19 FEAT / journal read journal entries, update and delete them
  .eslintrc
  client/src/components/App.jsx
  client/src/components/Journal.jsx
  client/src/components/JournalBar.jsx
  client/src/components/JournalBarItem.jsx
  client/src/components/JournalEntry.jsx
  package-lock.json
  package.json
  server/index.js
  server/routers/index.js
  server/routers/journalController.js
Labels: READY

#14 Added Habits Functionality
  client/dist/index.html
  client/dist/main.js
  client/src/components/App.jsx
  client/src/components/HabitElement.jsx
  client/src/components/HabitForm.jsx
  client/src/components/Habits.jsx
  server/db/index.js
  server/db/seed.js
  server/index.js
  server/routers/habitsController.js
  server/routers/index.js
Labels: DRAFT

#21 Feat /moods routes added for moods and list is rendered to the page
  .gitignore
  client/src/components/Mood.jsx
  client/src/components/Moods.jsx
  client/src/components/MoodsChart.jsx
  package-lock.json
  package.json
Labels: READY

#27 Update index.html to include tab title
  client/index.html
Labels: READY

#28 FEAT / journal updated styling
  client/src/components/Journal.jsx
  client/src/components/JournalBar.jsx
Labels: READY

#26 FEAT / navbar replaced nav bar with collapsible drawer navigator
  client/src/components/App.jsx
  client/src/components/DrawerContents.jsx
  client/src/components/NavBar.jsx
Labels: READY

#24 fix /added routes back for moods
  .gitignore
  client/src/components/App.jsx
  client/src/components/Moods.jsx
  package-lock.json
Labels: READY

#22 FEAT /home changed styling of HomePage and Weather components and added style sheet
  client/src/components/HomePage.jsx
  client/src/components/Weather.jsx
  client/src/components/floweraura.jpeg
  client/src/components/styles.js
  client/src/fonts/Voguella.ttf
  client/src/fonts/fonts.css
  client/src/index.jsx
  package-lock.json
  package.json
  server/routers/index.js
  server/routers/userController.js
  server/routers/weatherController.js
  webpack.config.js
Labels: READY

#31 FEAT / login fixed styling
  .gitignore
  client/src/components/Login.jsx
Labels: READY

#33 update /added styling to Moods feature
  client/src/components/Moods.jsx
  client/src/components/MoodsChart.jsx
Labels: READY

#36 update /added request handling, and routes. Request handling is not r…
  client/src/components/Moods.jsx
  server/db/index.js
  server/db/seed.js
  server/index.js
  server/routers/index.js
  server/routers/moodsController.js
  server/routers/userController.js
Labels: READY

#40 update /added text above list
  client/src/components/Moods.jsx
Labels: READY

#43 update /added comments
  client/src/components/Moods.jsx
  client/src/components/MoodsChart.jsx
  server/db/index.js
  server/routers/moodsController.js
Labels: READY

#41 ADD comments
  README.md
  client/src/components/App.jsx
  client/src/components/Journal.jsx
  client/src/components/JournalBarItem.jsx
  client/src/components/JournalEntry.jsx
  server/db/index.js
  server/db/seed.js
  server/index.js
  server/middleware/auth.js
  server/routers/index.js
  server/routers/journalController.js
  server/routers/userController.js
Labels: READY

#44 added text
  CONTRIBUTING.md
Labels: READY
